### ISSUE TITLE
Documentation & Missing Files to Reproduce Published Results

### ISSUE THREAD

**Issue by lrossouw** [Percept-Health-Solve/seir-model#4]
Please provide documentation on how to reproduce at least one of the published results.  It's not clear how to do so from the model provided.

**Comment by lrossouw** [comment]
It looks like we need to run `test_wrapper_var_params.py` but `data/calibration.xlsx` is not provided.

**Comment by lrossouw** [comment]
The following files are missing:

* `data/calibration.xlsx`
* `data/Startpop_2density_0comorbidity.csv`

**Comment by jasonrobwebster** [comment]
Both files have now been added. Documentation is still WIP - but you're right, the main file you need is the `test_wrapper_var_params.py`

**Comment by lrossouw** [comment]
Thanks I'm able to reproduce results of S1 visually at least.

Closed by 76ba97d21488eae137340a9948dec01981f3f869
